name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        symfony-version: ['^6.4', '^7.0']
        exclude:
          - php-version: '8.1'
            symfony-version: '^7.0'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require symfony/framework-bundle:${{ matrix.symfony-version }} --no-update
          composer update --no-progress

      - name: Cache PHP-CS-Fixer results
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-php-cs-fixer-${{ hashFiles('.php-cs-fixer.dist.php') }}

      - name: Run PHP-CS-Fixer
        run: composer cs:check

      - name: Cache Psalm results
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/psalm
            psalm.cache
          key: ${{ runner.os }}-psalm-${{ hashFiles('psalm.xml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-psalm-${{ hashFiles('psalm.xml') }}-
            ${{ runner.os }}-psalm-

      - name: Run Psalm
        run: composer psalm

      - name: Run tests
        run: composer test
